# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExceltoCSV.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 382)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(300, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("KoPub돋움체 Bold")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.lineEdit_csvpath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_csvpath.setGeometry(QtCore.QRect(190, 110, 321, 31))
        self.lineEdit_csvpath.setObjectName("lineEdit_csvpath")
        self.label_csvfile = QtWidgets.QLabel(self.centralwidget)
        self.label_csvfile.setGeometry(QtCore.QRect(130, 120, 56, 12))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_csvfile.setFont(font)
        self.label_csvfile.setObjectName("label_csvfile")
        self.btn_csv_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_csv_search.setGeometry(QtCore.QRect(520, 110, 91, 31))
        self.btn_csv_search.setObjectName("btn_csv_search")
        self.label_savepath = QtWidgets.QLabel(self.centralwidget)
        self.label_savepath.setGeometry(QtCore.QRect(100, 170, 91, 20))
        self.label_savepath.setObjectName("label_savepath")
        self.lineEdit_savepath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_savepath.setGeometry(QtCore.QRect(190, 160, 321, 31))
        self.lineEdit_savepath.setObjectName("lineEdit_savepath")
        self.btn_savefile_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_savefile_search.setGeometry(QtCore.QRect(520, 160, 91, 31))
        self.btn_savefile_search.setObjectName("btn_savefile_search")
        self.check_rmv_header = QtWidgets.QCheckBox(self.centralwidget)
        self.check_rmv_header.setGeometry(QtCore.QRect(240, 210, 131, 16))
        self.check_rmv_header.setObjectName("check_rmv_header")
        self.btn_convert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_convert.setGeometry(QtCore.QRect(240, 250, 211, 41))
        self.btn_convert.setObjectName("btn_convert")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 747, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Exel to CSV"))
        self.label_csvfile.setText(_translate("MainWindow", "csv 파일"))
        self.btn_csv_search.setText(_translate("MainWindow", "찾기"))
        self.label_savepath.setText(_translate("MainWindow", "파일 저장 경로"))
        self.btn_savefile_search.setText(_translate("MainWindow", "찾기"))
        self.check_rmv_header.setText(_translate("MainWindow", "첫 헤더 지우기"))
        self.btn_convert.setText(_translate("MainWindow", "변환하기"))
